Repository dashai/dashai, pull requests merged in 2018-05, with the labels that each got.

#21 Updates to fedora doco
  docs/00_deploy_openshift_onfedora27_via_oc_cluster_up/README.md
Labels: doco

#22 Update readme.md
  README.md
  docs/images/dashai.png
Labels: enhancement

#23 Add contributing guide
  CONTRIBUTING.md
Labels: doco

#41 Fix logo and Dashai on the README
  README.md
Labels: bug
